# .render.yaml
services:
  - type: web
    name: telegram-bot
    runtime: python
    pythonVersion: 3.12.7
    buildCommand: pip install python-telegram-bot==20.6 openai==1.35.10
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
        fromSecret: BOT_TOKEN
